acs/urls.py
'''
    VERIDIC - Towards a centralized access control system

    Copyright (C) 2011  Mikael Ates

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import settings
from django.conf.urls.defaults import url, include, patterns
from django.contrib import admin

from acs.forms import AuthenticRegistrationForm

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'acs.main_views.index'),

    url(r'^accounts/register',
       'registration.views.register',
       {'form_class': AuthenticRegistrationForm},
       name='registration_register',
       ),
    (r'^accounts/', include('registration.urls')),


    url(r'^login$', 'acs.main_views.login'),
    url(r'^logout$', 'acs.main_views.logout', name='auth_logout'),


    url(r'^ask_decision$', 'acs.views.ask_decision'),
    url(r'^ask_decision_regex$', 'acs.views.ask_decision_regex'),

    url(r'^graph$', 'acs.views.graph'),


    url(r'^create_policy_view$',
        'acs.main_views.create_policy_view'),
    url(r'^delete_policy_view$',
        'acs.main_views.delete_policy_view'),
    url(r'^mod_policy$', 'acs.main_views.mod_policy'),


    url(r'^synchronize_users_in_policy_view$',
        'acs.alias_mgmt_views.synchronize_users_in_policy_view'),
    url(r'^all_users_self_admin$',
        'acs.alias_mgmt_views.all_users_self_admin'),
    url(r'^list_users_for_aliases$',
        'acs.alias_mgmt_views.list_users_for_aliases'),
    url(r'^list_aliases$',
        'acs.alias_mgmt_views.list_aliases'),
    url(r'^switch_self_admin$',
        'acs.alias_mgmt_views.switch_self_admin'),
    url(r'^set_user_in_policy_from_home$',
        'acs.alias_mgmt_views.set_user_in_policy_from_home'),
    url(r'^add_alias_only$',
        'acs.alias_mgmt_views.add_alias_only'),
    url(r'^list_aliases_in_policy$',
        'acs.alias_mgmt_views.list_aliases_in_policy'),
    url(r'^set_user_in_policy$',
        'acs.alias_mgmt_views.set_user_in_policy'),
    url(r'^set_user_in_source$',
        'acs.alias_mgmt_views.set_user_in_source'),


    url(r'^list_accesses$',
        'acs.delegation_views.list_accesses'),
    url(r'^list_delegated_permissions$',
        'acs.delegation_views.list_delegated_permissions'),
    url(r'^delegate_access$',
        'acs.delegation_views.delegate_access'),


    url(r'^add_user$',
        'acs.user_mgmt_views.add_user'),
    url(r'^manage_root_administrators$',
        'acs.user_mgmt_views.manage_root_administrators'),
    url(r'^manage_user_administrators$',
        'acs.user_mgmt_views.manage_user_administrators'),
    url(r'^manage_abac_administrators$',
        'acs.user_mgmt_views.manage_abac_administrators'),
    url(r'^manage_policy_administrators$',
        'acs.user_mgmt_views.manage_policy_administrators'),


    url(r'^list_users$',
        'acs.views.list_users'),

    url(r'^add_role$', 'acs.views.add_role'),
    url(r'^add_object$', 'acs.views.add_object'),
    url(r'^add_view$', 'acs.views.add_view'),
    url(r'^add_action$', 'acs.views.add_action'),
    url(r'^add_activity$', 'acs.views.add_activity'),
    url(r'^add_permission$', 'acs.views.add_permission'),
    url(r'^add_permission_any$', 'acs.views.add_permission_any'),

    url(r'^list_roles$', 'acs.views.list_roles'),
    url(r'^list_objects$', 'acs.views.list_objects'),
    url(r'^list_views$', 'acs.views.list_views'),
    url(r'^list_actions$', 'acs.views.list_actions'),
    url(r'^list_activities$', 'acs.views.list_activities'),
    url(r'^list_permissions$', 'acs.views.list_permissions'),

    url(r'^mod_user$', 'acs.views.mod_user'),
    url(r'^mod_role$', 'acs.views.mod_role'),
    url(r'^mod_object$', 'acs.views.mod_object'),
    url(r'^mod_view$', 'acs.views.mod_view'),
    url(r'^mod_action$', 'acs.views.mod_action'),
    url(r'^mod_activity$', 'acs.views.mod_activity'),

    url(r'^del_any$', 'acs.deletion_view.del_any'),
    url(r'^del_permission$', 'acs.views.del_permission'),

    url(r'^add_abac_permission$', 'acs.abac_views.add_abac_permission'),
    url(r'^list_abac_permissions$', 'acs.abac_views.list_abac_permissions'),
    url(r'^del_abac_permission$', 'acs.abac_views.del_abac_permission'),
    url(r'^add_abac_source$', 'acs.views.add_abac_source'),
    url(r'^add_abac_ldap_source$', 'acs.views.add_abac_ldap_source'),
    url(r'^list_abac_sources$', 'acs.views.list_abac_sources'),
    url(r'^mod_source$', 'acs.views.mod_source'),

    url(r'^add_admin_view$',
        'acs.acs_administration_views.add_admin_view'),
    url(r'^list_admin_views$',
        'acs.acs_administration_views.list_admin_views'),
    url(r'^add_admin_role$',
        'acs.acs_administration_views.add_admin_role'),
    url(r'^list_admin_roles$',
        'acs.acs_administration_views.list_admin_roles'),
    url(r'^add_admin_permission$',
        'acs.acs_administration_views.add_admin_permission'),
    url(r'^list_admin_permissions$',
        'acs.acs_administration_views.list_admin_permissions'),
    url(r'^mod_admin_view$',
        'acs.acs_administration_views.mod_admin_view'),
    url(r'^mod_admin_role$',
        'acs.acs_administration_views.mod_admin_role'),


#    url(r'^delegate_permissions$', 'acs.views.delegate_permissions'),
#    url(r'^remove_delegations$', 'acs.views.remove_delegations'),

    url(r'^incoming$', 'acs.net_interface.incoming'),
    #url(r'^outcoming$', 'acs.net_interface.outcoming'),

    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.STATIC_SERVE:
    urlpatterns += patterns('',
        url(
            regex = r'^media/(?P<path>.*)$',
            view = 'django.views.static.serve',
            kwargs = {'document_root': settings.MEDIA_ROOT}),
    )

acs/attribute_aggregator/models.py
'''
    VERIDIC Project - Towards a centralized access control system

    Copyright (C) 2011  Mikael Ates

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''


import datetime
import logging

from cPickle import loads, dumps

from django.utils.translation import ugettext as _
from django.db import models
from django.contrib.auth.models import User
try:
    import ldap
except ImportError:
    ldap = None

from acs.attribute_aggregator.signals import any_attributes_call, \
    listed_attributes_call, listed_attributes_with_source_call
from acs.attribute_aggregator.mapping import ATTRIBUTE_MAPPING, \
    ATTRIBUTE_NAMESPACES
from acs.attribute_aggregator.core import convert_from_string, \
    get_def_name_from_name_and_ns_of_attribute, iso8601_to_datetime, \
    get_def_name_from_oid, get_def_name_from_alias, \
    is_alias_of_definition, is_oid_of_definition


logger = logging.getLogger('attribute_aggregator')


ATTRIBUTES_NS = [('Default', 'Default')] \
    + [(ns, ns) for ns in ATTRIBUTE_NAMESPACES]


class AttributeSource(models.Model):
    name = models.CharField(
        verbose_name = _("Name"),
        max_length = 200, unique=True)
    namespace = models.CharField(
        verbose_name = _("Namespace"),
        max_length = 100,
        choices = ATTRIBUTES_NS, default = ATTRIBUTES_NS[0])

    def __unicode__(self):
        return self.name

    def get_source_instance(self):
        try:
            return self.ldapsource
        except:
            pass
        return None


def get_source_from_name(name):
    try:
        return AttributeSource.objects.get(name=name)
    except:
        return None


def get_all_sources():
    try:
        return AttributeSource.objects.all()
    except:
        return None

if ldap:
    class LdapSource(AttributeSource):
        server = models.CharField(
            verbose_name = _("Server"),
            max_length=200, unique=True)
        user = models.CharField(
            verbose_name = _("User"),
            max_length=200, blank=True, null=True)
        password = models.CharField(
            verbose_name = _("Password"),
            max_length=200, blank=True, null=True)
        base = models.CharField(
            verbose_name = _("Base"),
            max_length=200)
        port = models.IntegerField(
            verbose_name = _("Port"),
            default=389)
        ldaps = models.BooleanField(
            verbose_name = _("LDAPS"),
            default=False)
        certificate = models.TextField(
            verbose_name = _("Certificate"),
            blank=True)
        is_auth_backend = models.BooleanField(
            verbose_name = _("Is it used for authentication?"),
            default=False)

        def __init__(self, *args, **kwargs):
            super(LdapSource, self).__init__(*args, **kwargs)
            self.namespace = "X500"

class UserAliasInSource(models.Model):
    name = models.CharField(
        verbose_name = _("Name"),
        max_length = 200)
    source = models.ForeignKey(AttributeSource,
        verbose_name = _('Attribute Source'))
    user = models.ForeignKey(User,
        verbose_name = _("User"),
        related_name='user_alias_in_source')

    class Meta:
        verbose_name = _('alias in source')
        verbose_name_plural = _('aliases in source')
        unique_together = ("name", "source")

    def __unicode__(self):
        return "alias %s of user %s in %s" % (self.name, self.user,
            self.source)


class AttributeData:

    def __init__(self, definition, values=None, source=None,
            expiration_date=None):
        '''
            definition can be given by its name, an alias or an oid
        '''
        self.definition = None
        if definition in ATTRIBUTE_MAPPING:
            self.definition = definition
        else:
            d = get_def_name_from_oid(definition)
            if d:
                self.definition = d
            else:
                self.definition = get_def_name_from_alias(definition)
        if not self.definition:
            raise Exception('Definition not found.')
        self.values = list()
        if values:
            for value in values:
                if convert_from_string(self.definition, value):
                    self.values.append(value.encode('utf-8'))
        if isinstance(source, AttributeSource):
            self.source_id = source.id
        else:
            self.source_id = -1
        '''ISO8601'''
        try:
            iso8601_to_datetime(expiration_date)
            self.expiration_date = expiration_date
        except:
            self.expiration_date = None

    def get_definition(self):
        return self.definition

    def get_full_definition(self):
        if not self.definition in ATTRIBUTE_MAPPING:
            return None
        return ATTRIBUTE_MAPPING[self.definition]

    def get_exptime_in_iso8601(self):
        return self.expiration_date

    def get_exptime_in_datetime(self):
        return iso8601_to_datetime(self.expiration_date)

    def set_exptime_in_iso8601(self, expiration_date):
        try:
            iso8601_to_datetime(expiration_date)
            self.expiration_date = expiration_date
        except:
            self.expiration_date = None
        self.save()
        return self.expiration_date

    def set_exptime_in_datetime(self, expiration_date):
        try:
            self.expiration_date = expiration_date.isoformat()
        except:
            self.expiration_date = None
        self.save()
        return self.expiration_date

    def get_values(self):
        if self.values:
            return [value.decode('utf-8') for value in self.values]
        return list()

    def get_converted_values(self):
        return [convert_from_string(self.definition, value) \
            for value in self.values]

    def get_source(self):
        try:
            return AttributeSource.objects.get(pk=self.source_id)
        except:
            return None

    def get_source_id(self):
        return self.source_id

    def add_value(self, value):
        if value and convert_from_string(self.definition, value):
            try:
                self.values.append(value.encode('utf-8'))
                self.save()
                return 0
            except:
                return -1
        return -1

    def remove_value(self, value):
        if value:
            try:
                self.values.remove(value.encode('utf-8'))
                self.save()
                return 0
            except:
                return -1
        return -1

    def does_expire(self):
        if self.expiration_date:
            return self.expiration_date
        else:
            return 0

    def __unicode__(self):
        s = "AttributeData"
        values = self.get_values()
        if values:
            s += " %s with values %s" % (self.get_definition(), values)
        source = self.get_source()
        if source:
            s += " from %s" % str(source)
        if self.does_expire():
            s += " (Expires on %s)" % self.does_expire()
        return s


class UserAttributeProfile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True,
        related_name='user_attribute_profile')
    data = models.TextField(null=True, blank=True)

    def add_data(self, data):
        if not isinstance(data, AttributeData):
            return -1
        try:
            l = None
            if not self.data:
                l = list()
            else:
                l = loads(str(self.data))
            l.append(data)
            self.data = dumps(l)
        except:
            return -1
        self.save()
        return 0

    def remove_data(self, position):
        try:
            l = loads(str(self.data))
            res = l.pop(position)
            self.data = dumps(l)
            return res
        except:
            return None

    def get_all_data(self):
        try:
            l = loads(str(self.data))
            return l
        except:
            return []

    def get_data_of_definition(self, definition, in_list=None):
        '''
            definition can be given by its name, an alias or an oid
        '''
        l = None
        if in_list:
            l = in_list
        else:
            l = self.get_all_data()
        if not l:
            return []
        return [d for d in l if d.get_definition() == definition \
            or is_alias_of_definition(d.get_definition(), definition) \
            or is_oid_of_definition(d.get_definition(), definition)]

    def get_freshest_data_of_definition(self, definition):
        l = self.get_data_of_definition(definition)
        if not l:
            return []
        l.sort(key=lambda x: x.expiration_date, reverse=True)
        return l[0]

    def get_data_of_source(self, source, in_list=None):
        l = []
        if in_list:
            l = in_list
        else:
            l = self.get_all_data()
        if not l or not isinstance(source, AttributeSource):
            return []
        return [d for d in l if d.get_source_id() == source.id]

    def get_data_of_source_by_name(self, source):
        l = self.get_all_data()
        if not l:
            return []
        s = []
        try:
            s = AttributeSource.objects.get(name=source)
        except:
            return []

acs/templates/add_alias_only.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if title %}
<h2>{{ title }}</h2>
{% else %}
<h2>{% trans "Add an entity" %}</h2>
{% endif %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

  <div>
  <form method="post" action="">
    <p>{% trans "Alias" %}: <input id="id_alias" type="text" name="alias" maxlength="30" /></p>
    <input id="id_namespace" type="hidden" name="namespace" value="{{ policy.namespace.id}}"/>
    <input type="submit" name="{{ submit_name }}" value="{% trans "Add" %}"/>
    <input type="submit" name="cancel" value="{% trans 'Cancel' %}"/>
  </form>
  </div>
{% endblock %}

acs/templates/add_permission.html
{% extends "base.html" %}
{% load i18n %}
{% load acs_filters %}

{% block content %}

{% if title %}
<h2>{{ title }}</h2>
{% endif %}

{% if messages %}
<p>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</p>
{% endif %}

{% if who_to_display and what_to_display and how_to_display %}
<div>
<form method="post" action="">
    <p>
    <h3>{% trans "Who" %}</h3>
    <select name="who_matches" id="id_who_matches">
    {% for it in who_to_display %}
        {% if it|klass == "UserAlias" %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.alias }}</option>
        {% else %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.name }}</option>
        {% endif %}
    {% endfor %}
    </select>
    </p>
    <p>
    <h3>{% trans "What" %}</h3>
    <select name="what_matches" id="id_what_matches">
    {% for it in what_to_display %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.name }}</option>
    {% endfor %}
    </select>
    </p>
    <p>
    <h3>{% trans "How" %}</h3>
    <select name="how_matches" id="id_how_matches">
    {% for it in how_to_display %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.name }}</option>
    {% endfor %}
    </select>
    </p>
    <p>
    <br style="clear: both;"/>
    <label>{% trans "Can be delegated?" %}<input type="checkbox" name="delegable" value="delegable" checked="checked"/></label>
    </p>
    <p>
    <br style="clear: both;"/>
    <input type="submit" name="{{ submit_name }}" value="{% trans "Add" %}"/>
    </p>
</form>
</div>
{% else %}
<p>{% trans 'You have not enough rights or there is not enough material in the policy to set a to set a permission.' %}</p>
{% endif %}

<div class="right">
<a class="back" href="{{ backlink }}">{% trans "Back" %}</a>
</div>
{% endblock %}

acs/templates/ask_decision.html
{% extends "base.html" %}
{% load i18n %}
{% load acs_filters %}

{% block content %}

{% if title %}
<h2>{% trans "Ask for a decision" %}</h2>
{% endif %}

<p>
You can only ask decisions on entities you have administration rights.
</p>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if who_to_display and what_to_display and how_to_display %}
<div>
<form method="post" action="">
{% if who_to_display %}
    <p>
    <h3>{% trans "Who" %}</h3>
    <select name="who_matches" id="id_who_matches">
    {% for it in who_to_display %}
        {% if it|klass == "UserAlias" %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.alias }}</option>
        {% else %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.name }}</option>
        {% endif %}
    {% endfor %}
    </select>
    </p>
{% endif %}
{% if what_to_display %}
    <p>
    <h3>{% trans "What" %}</h3>
    <select name="what_matches" id="id_what_matches">
    {% for it in what_to_display %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.name }}</option>
    {% endfor %}
    </select>
    </p>
{% endif %}
{% if how_to_display %}
    <p>
    <h3>{% trans "How" %}</h3>
    <select name="how_matches" id="id_how_matches">
    {% for it in how_to_display %}
        <option value="{{ it.id }}_{{ it|klass }}">{{ it.name }}</option>
    {% endfor %}
    </select>
    </p>
{% endif %}
    <p>
    <br style="clear: both;"/>
    <input type="submit" name="{{ submit_name }}" value="{% trans "Ask" %}"/>
    </p>
</form>
</div>
{% else %}
<p>{% trans 'You have not enough rights or there is not enough material in the policy to ask for a decision.' %}</p>
{% endif %}

<div class="right">
<a class="back" href="{{ backlink }}">{% trans "Back" %}</a>
</div>
{% endblock %}

acs/templates/base.html
{% load i18n %} <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/style.css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/jquery-ui.custom.css" />
    <title>{% block title %}Access Control System{% endblock %}</title>
    {% block extra_scripts %}
    {% endblock %}
</head>

<body {% block bodyargs %}{% endblock %} >
  <div id="wrap">
    <a href="/"><div id="header">
      {% block header %}
      <h1>A.C.S.</h1>
      <span>Decide for me</span>
      {% endblock %}
    </div></a>

    <div id="splash"></div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        Copyright &copy; 2011 Entr'ouvert
        {% endblock %}
    </div>
  </div>
</body>

</html>

acs/templates/create_policy.html
{% extends "base.html" %}
{% load i18n %}
{% load acs_filters %}

{% block content %}
<h2>{% trans "Create a policy for a new application" %}</h2>

{% if messages %}
<p>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</p>
{% endif %}

<div>
<form method="post" action="">
    <p><label for="id_name">{% trans "name:" %}</label> <input id="id_name" type="text" name="name" maxlength="30" /></p>
    <p><label for="id_namespace">{% trans "namespace:" %}</label> <input id="id_namespace" type="text" name="namespace" maxlength="30" /> If not given, the name will be taken as a namespace.</p>
    <br style="clear: both;"/>
    <input type="submit" name="{{ submit_name }}" value="{% trans "Add" %}"/>
    <input type="submit" name="cancel" value="{% trans 'Cancel' %}"/>
    </p>
</form>
</div>
{% endblock %}

acs/templates/deletion_confirmation.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if item %}
<h2>{% trans "Are you sure you want to delete" %} {{ item }} ?</h2>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if admin_deletion %}
<ul>
    {% for c in admin_deletion %}
    <li>{{ c }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if collateral_damages %}
<p>{% trans "You will also delete these objects:" %}</p>
<ul>
    {% for c in collateral_damages %}
    <li>{{ c }}</li>
    {% endfor %}
</ul>
{% endif %}

<form method="post" action="/del_any">
    <input type="hidden" name="type_entity" value="{{ type_entity }}"/>
    <input type="hidden" name="id" value="{{ item.id }}"/>
    <input type="hidden" name="consent" value="consent"/>
    {% if back_url %}<input type="hidden" name="back_url" value="{{ back_url }}"/>{% endif %}
    <input type="submit" name="Delete" value="{% trans "Delete" %}"/>
    <input type="submit" name="Cancel" value="{% trans "Cancel" %}"/>
</form>

{% else %}
<p>Something bad happened.</p>
<div class="right">
<a class="back" href="/">{% trans "Back" %}</a>
</div>
{% endif %}
{% endblock %}

acs/templates/empower_or_downgrade.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if title %}
<h2>{{ title }}</h2>
{% endif %}
{% if subtitle %}
<h3>{{ subtitle }}</h3>
{% endif %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if not_manageable %}
{% if explanation %}
<h4>{{ explanation }}</h4>
{% endif %}
<ul>
    {% for user in not_manageable %}
    <li><p>
      <label>{{ user.username }}</label>
    </p></li>
    {% endfor %}
</ul>
{% endif %}

{% if not_empowered or empowered %}
<h4>{% trans "Users you can administrate:" %}</h4>

{% if not_empowered %}
<ul>
    {% for user in not_empowered %}
    <li><p>
      <label>{{ user.username }}</label>
      <form method="post" action="">
        <input type="hidden" name="id" value="{{ user.id }}"/>
        <input type="hidden" name="type" value="{{ type_admin }}"/>
        <input type="submit" name="empower" value="{% trans "Empower" %}"/>
      </form>
    </p></li>
    {% endfor %}
</ul>
{% endif %}

{% if empowered %}
<ul>
    {% for user in empowered %}
    <li><p>
      <label>{{ user.username }}</label>
      <form method="post" action="">
        <input type="hidden" name="id" value="{{ user.id }}"/>
        <input type="hidden" name="type" value="{{ type_admin }}"/>
        <input type="submit" name="downgrade" value="{% trans "Downgrade" %}"/>
      </form>
    </p></li>
    {% endfor %}
</ul>
{% endif %}
{% else %}
<p>
There is no user you are authorized to administrate.
</p>
{% endif %}

<div class="right">
<a class="back" href="{{ backlink }}">{% trans "Back" %}</a>
</div>
{% endblock %}

acs/templates/graph.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if graphs %}
<p>Access control policy</p>
{% for g in graphs %}
<p><img src="{{ MEDIA_URL }}images/{{ g }}" width=600/></p>
{% endfor %}
{% endif %}

{% if backlink %}
<div class="right">
<a class="back" href="{{ backlink }}">{% trans "Back" %}</a>
</div>
{% else %}
<div class="right">
<a class="back" href="/">{% trans "Back" %}</a>
</div>
{% endif %}
{% endblock %}

acs/templates/list_abac_permissions.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if title %}
<h2>{{ title }}</h2>
{% else %}
<h2>{% trans "Modify or delete an ABAC permission" %}</h2>
{% endif %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if list_any %}
<ul>
    {% for p in list_any %}
    <li class="bigbutton">
    <p>{{ p }}</p>
    <form method="post" action="/del_abac_permission">
        {% if back_url %}<input type="hidden" name="back_url" value="{{ back_url }}"/>{% endif %}
        <input type="hidden" name="id" value="{{ p.id }}"/>
        <input type="submit" name="Delete" value="{% trans "Delete" %}"/>
    </form>
    </li>
    {% endfor %}
</ul>
{% endif %}
<div class="right">
<a class="back" href="{{ backlink }}">{% trans "Back" %}</a>
</div>
{% endblock %}